#Metrics related configurations
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
