version: '2'
services:
  eureka-server:
    image: ${VERSIONED_IMAGE}
    container_name: 'spring-boot-config-demo'
    env_file:
      - demo.env
    ports:
     - "8080:8080"
    extra_hosts:
     - "peer1:192.168.10.211"
     - "peer2:192.168.10.212"
     - "peer3:192.168.10.213"