version: '2'
services:
  spring-boot-config-demo:
    image: ${VERSIONED_IMAGE}
    container_name: 'spring-boot-config-demo'
    command: SPRING_APPLICATION_JSON='{"foo":{"bar":"spam"}}' java -jar /app.jar --debug
    ports:
     - "8080:8080"
    extra_hosts:
     - "peer1:192.168.10.211"
     - "peer2:192.168.10.212"
     - "peer3:192.168.10.213"